# Introducción a Numpy
Numpy es una librería de cálculo numérico y matricial para python.
Contiene muchas funciones para la manipulación de matrices y arrays multidimensionales. Las funciones de numpy estan optimizadas para una ejecución más veloz en el procesador.

Es recomendable redefinir las operacioens matriciales para aprovechar los algoritmos optimizados de numpy. Esta operación se conoce como **vectorizar** el código.

In [2]:
# importamos la librería como un alias
import numpy as np

## Arrays

Los arrays de numpy se pueden inicializar con listas comunes de python.
Las listas deben contener elementos del **mismo tipo**.

In [3]:
a = np.array([1, 2, 3])
print(type(a))
# para imprimir las dimensiones de la matriz
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [5]:
mat = [[1, 2, 3], [4, 5, 6]]
print(mat)
print(mat[0])
print(mat[1][1])

[[1, 2, 3], [4, 5, 6]]
[1, 2, 3]
5


In [24]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.shape)
print(b[0, 0])
print(b)

(2, 3)
1
[[1 2 3]
 [4 5 6]]


In [21]:
c = np.array([[[1, 2, 3], [4, 5, 6]], [[56, 66, 76], [14, 15, 16]]])
print(c.shape)
print(c[0, 1])
print(c)

(2, 2, 3)
[4 5 6]
[[[ 1  2  3]
  [ 4  5  6]]

 [[56 66 76]
  [14 15 16]]]


## Creación de matrices especiales (contenedores)


In [12]:
# matriz llena de ceros
a = np.zeros((2, 4, 3))
print(a)
print(a.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(2, 4, 3)


In [13]:
filas = 3
cols = 4
matriz = []
for f in range(filas):
    fila = [0 for c in range(cols)]
    matriz.append(fila)

print(matriz)
print(len(matriz), len(matriz[0]))

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
3 4


In [14]:
# matriz llena de unos
b = np.ones((4, 4))
print(b)
print(b.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [16]:
# matriz llena de valores
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [17]:
np.ones((2, 2)) * 7

array([[7., 7.],
       [7., 7.]])

In [19]:
# matriz identidad
d = np.eye(4)
print(d)
print(d.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)


In [20]:
# matriz con valores aleatorios
e = np.random.random((5, 3))
print(e)
print(e.shape)

[[0.28442488 0.11039245 0.19887463]
 [0.30359507 0.43172399 0.32085686]
 [0.18521762 0.50299705 0.55363872]
 [0.57899259 0.56581088 0.8179157 ]
 [0.50175437 0.7241587  0.70923411]]
(5, 3)


## Array indexing
Una de las funcionalidades más interesantes de numpy es la indexación de arrays multidimensionales.

In [25]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print(a.shape)
# acceso a un elemento 
print(a[1, 2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
7


In [31]:
# acceso mediante rangos
b = a[-2:,1:3]
print(b)

[[ 6  7]
 [10 11]]


In [ ]:
b[0, 0] = 77
print(b)

In [35]:
# extraccion de filas y rangos de filas
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
col = a[:, 2:3]        # vector
print(col)
# row_r2 = a[1:2, :]      # rangos: matriz
# print(row_r1, row_r1.shape)
# print(row_r2, row_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 3]
 [ 7]
 [11]]


In [36]:
# extracción de columnas y rangos de columnas
col_r1 = a[:, 2]        # vector
col_r2 = a[:, 2:3]      # matriz
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 3  7 11] (3,)
[[ 3]
 [ 7]
 [11]] (3, 1)


## Array math
Numpy ofrece numerosas funciones para realizar operaciones matemáticas con arrays multidimensionales.

In [41]:
# element wise addition
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 3]], dtype=np.float64)
print(x + y)
print(np.add(x, y))
print(x + y == np.add(x, y))

[[ 6.  8.]
 [10.  7.]]
[[ 6.  8.]
 [10.  7.]]
[[ True  True]
 [ True  True]]


In [42]:
# element wise substraction
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4.  1.]]
[[-4. -4.]
 [-4.  1.]]


In [43]:
# element wise multiplication
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 12.]]
[[ 5. 12.]
 [21. 12.]]


In [44]:

print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 1.33333333]]
[[0.2        0.33333333]
 [0.42857143 1.33333333]]


In [45]:
# funciones especiales
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [46]:
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


In [47]:
# producto escalar
v = np.array([9, 10, 2])
w = np.array([11, 12, 3])

acum = 0
for i in range(v.size):
    prod = v[i] * w[i]
    acum += prod

print(f'bucle: {acum}')
print(v.dot(w))
print(np.dot(v, w))

bucle: 225
225
225


In [52]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6, 4, 5], [7, 8, 6, 5]])
# multiplicacion de matrices
print(x.shape, y.shape)

print(np.dot(x, y))

(2, 2) (2, 4)
[[19 22 16 15]
 [43 50 36 35]]
[[19 22 16 15]
 [43 50 36 35]]


In [ ]:
print(x.dot(y))
print(np.dot(x, y))

In [53]:
# reducción de matrices
x = np.array([[1, 2, 5, 6], [1, 2, 3, 4], [4, 3, 2, 1]])
print(x)
print(np.sum(x))
# sobre columnas: axis = 1
print(np.sum(x, axis=1))
# sobre filas: axis = 0
print(np.sum(x, axis=0))

print(np.sum(x, axis=1, keepdims=True))

[[1 2 5 6]
 [1 2 3 4]
 [4 3 2 1]]
34
[14 10 10]
[ 6  7 10 11]
[[14]
 [10]
 [10]]


In [54]:
# matriz traspuesta
x = np.array([[1, 2], [3, 4], [5, 6]])
print(x, x.shape)
print(x.T, x.T.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 3 5]
 [2 4 6]] (2, 3)


In [55]:
v = np.array([1, 2, 3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


## Matplotlib

### Plotting

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

x = np.arange(0, 2 * np.pi, 0.1)
y = x**2

plt.plot(x, y)


In [ ]:
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('time')
plt.ylabel('voltage')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

### Subplots

In [ ]:
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

plt.subplot(121)
plt.plot(x, y_sin)
plt.title('Sine')

plt.subplot(122)
plt.plot(x, y_cos)
plt.title('Cosine')
plt.show()

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.linalg.eigvalsh(x)
print(d)

## Notas finales
Numpy reemplaza gran parte de la funcionalidad del lenguaje de programación de MATLAB para la manipulación de arrays multidimensionales y la vectorización de operaciones. Sin embargo, la ventaja de numpy es que cuenta con la gran popularidad y capacidad de python con el cual podemos crear desde aplicaciones web hasta sistemas de inteligencia artificial.
Para las personas que tienen un background de MATLAB se puede consultar este [cheatsheet](http://mathesaurus.sourceforge.net/matlab-numpy.html)
con equivalencias en funciones y operaciones.
